// 100 interesting legal facts about Pakistan
export const pakistanLegalFacts = [
  "Pakistan's legal system is based on English common law, with Islamic law (Sharia) playing a significant role in personal and family matters.",
  "The Constitution of Pakistan was adopted in 1973 and is the supreme law of the country.",
  "Pakistan has a three-tier judicial system: Supreme Court, High Courts, and District Courts.",
  "The Supreme Court of Pakistan is the highest court and has original, appellate, and advisory jurisdiction.",
  "Pakistan has four High Courts: Lahore, Karachi, Peshawar, and Balochistan High Courts.",
  "The Federal Shariat Court was established in 1980 to examine laws for compliance with Islamic injunctions.",
  "Pakistan's legal profession is regulated by the Pakistan Bar Council and Provincial Bar Councils.",
  "The Limitation Act 1908 governs the time limits for filing civil suits in Pakistan.",
  "The Contract Act 1872 is the primary legislation governing contracts in Pakistan.",
  "Pakistan's Companies Act 2017 modernized corporate law and replaced the Companies Ordinance 1984.",
  "The Transfer of Property Act 1882 governs property transactions in Pakistan.",
  "Pakistan's labor laws are primarily governed by the Industrial Relations Act 2012.",
  "The Consumer Protection Act 2019 provides comprehensive protection to consumers in Pakistan.",
  "Pakistan's intellectual property laws are governed by the Copyright Ordinance 1962 and Patents Ordinance 2000.",
  "The Arbitration Act 1940 and Recognition and Enforcement Act 2011 govern arbitration in Pakistan.",
  "Pakistan's banking laws are primarily regulated by the State Bank of Pakistan Act 1956.",
  "The Securities and Exchange Commission of Pakistan (SECP) regulates corporate and capital markets.",
  "Pakistan's tax laws are governed by the Income Tax Ordinance 2001 and Sales Tax Act 1990.",
  "The National Accountability Bureau (NAB) Ordinance 1999 established Pakistan's anti-corruption body.",
  "Pakistan's family laws include the Muslim Family Laws Ordinance 1961 and Guardians and Wards Act 1890.",
  "The Dowry and Bridal Gifts (Restriction) Act 1976 restricts dowry practices in Pakistan.",
  "Pakistan's criminal law is primarily governed by the Pakistan Penal Code 1860.",
  "The Code of Criminal Procedure 1898 governs criminal procedure in Pakistan.",
  "The Qanun-e-Shahadat Order 1984 governs the law of evidence in Pakistan.",
  "Pakistan's environmental laws include the Pakistan Environmental Protection Act 1997.",
  "The Right to Information Act 2017 promotes transparency and accountability in Pakistan.",
  "Pakistan's cybercrime laws are governed by the Prevention of Electronic Crimes Act 2016.",
  "The Protection of Women (Criminal Laws Amendment) Act 2006 strengthened women's rights.",
  "Pakistan's anti-terrorism laws are primarily governed by the Anti-Terrorism Act 1997.",
  "The Legal Practitioners and Bar Councils Act 1973 regulates the legal profession.",
  "Pakistan's rent control laws vary by province, with each province having its own legislation.",
  "The Registration Act 1908 governs the registration of documents in Pakistan.",
  "Pakistan's succession laws are governed by the Succession Act 1925 for non-Muslims.",
  "The Muslim Personal Law (Shariat) Application Act 1962 applies Islamic law to Muslims.",
  "Pakistan's motor vehicle laws are governed by the Motor Vehicles Ordinance 1965.",
  "The Drugs Act 1976 regulates pharmaceutical products and controlled substances.",
  "Pakistan's media laws include the Pakistan Electronic Media Regulatory Authority (PEMRA) Ordinance 2002.",
  "The Competition Act 2010 promotes fair competition and prevents monopolies.",
  "Pakistan's insurance laws are regulated by the Insurance Ordinance 2000.",
  "The Foreign Exchange Regulation Act 1947 governs foreign currency transactions.",
  "Pakistan's immigration laws are primarily governed by the Foreigners Act 1946.",
  "The Public Procurement Regulatory Authority Ordinance 2002 governs government procurement.",
  "Pakistan's land revenue laws are governed by the Land Revenue Act 1967.",
  "The Cantonments Act 1924 governs administration in military cantonments.",
  "Pakistan's local government laws vary by province under the 18th Amendment.",
  "The Pakistan Medical and Dental Council Ordinance 1962 regulates medical practice.",
  "Pakistan's education laws include the Right to Free and Compulsory Education Act 2012.",
  "The Pakistan Telecommunication (Re-organization) Act 1996 regulates telecommunications.",
  "Pakistan's aviation laws are governed by the Civil Aviation Ordinance 1960.",
  "The Pakistan Standards and Quality Control Authority Act 1996 ensures product standards.",
  "Pakistan's mining laws are governed by the Mines Act 1923 and provincial regulations.",
  "The Pakistan Engineering Council Act 1975 regulates engineering practice.",
  "Pakistan's agricultural laws include the Agricultural Produce Markets Act 1939.",
  "The Pakistan Council of Scientific and Industrial Research Act 1953 promotes research.",
  "Pakistan's fisheries laws are governed by the Fisheries Ordinance 1961.",
  "The Pakistan Veterinary Medical Council Act 1996 regulates veterinary practice.",
  "Pakistan's forest laws include the Forest Act 1927 and provincial forest acts.",
  "The Pakistan Council for Science and Technology Act 1973 promotes scientific development.",
  "Pakistan's water laws are governed by the Water (Prevention and Control of Pollution) Act 1974.",
  "The Pakistan Nursing Council Act 1973 regulates nursing practice.",
  "Pakistan's pharmacy laws are governed by the Pharmacy Act 1967.",
  "The Pakistan Bar Council Rules regulate legal education and practice standards.",
  "Pakistan's alternative dispute resolution is promoted through the ADR Act 2017.",
  "The Pakistan Legal Practitioners and Bar Councils Rules 1976 govern legal practice.",
  "Pakistan's property laws include the Land Acquisition Act 1894 for government acquisitions.",
  "The Pakistan Penal Code includes specific provisions for cybercrimes and digital offenses.",
  "Pakistan's commercial laws are harmonized with international best practices.",
  "The Companies Act 2017 introduced concepts like single-member companies and corporate social responsibility.",
  "Pakistan's banking sector is regulated by both the State Bank and SECP.",
  "The Securities Act 2015 modernized capital markets regulation.",
  "Pakistan's tax system includes both federal and provincial taxes.",
  "The Sales Tax Act 1990 applies to goods, while services tax is governed separately.",
  "Pakistan's customs laws are governed by the Customs Act 1969.",
  "The Federal Excise Act 2005 governs excise duties on specific goods.",
  "Pakistan's property registration requires proper documentation and stamp duty payment.",
  "The Stamp Act 1899 governs stamp duties on documents.",
  "Pakistan's contract law recognizes both written and oral contracts.",
  "The Specific Relief Act 1877 provides remedies for breach of contract.",
  "Pakistan's employment laws include provisions for minimum wage and working hours.",
  "The Factories Act 1934 regulates working conditions in factories.",
  "Pakistan's social security laws include the Employees' Old-Age Benefits Institution Act 1976.",
  "The Workers' Welfare Fund Ordinance 1971 provides benefits to workers.",
  "Pakistan's consumer protection laws allow for compensation and product recalls.",
  "The Competition Commission of Pakistan enforces anti-competitive practices.",
  "Pakistan's intellectual property office is the Intellectual Property Organization (IPO).",
  "The Trademarks Ordinance 2001 protects brand names and logos.",
  "Pakistan's copyright law protects literary, artistic, and musical works.",
  "The Patents Ordinance 2000 provides protection for inventions.",
  "Pakistan's data protection laws are evolving with the Personal Data Protection Bill.",
  "The Prevention of Electronic Crimes Act includes provisions for data protection.",
  "Pakistan's family courts were established under the Family Courts Act 1964.",
  "The Muslim Family Laws Ordinance introduced reforms in marriage and divorce procedures.",
  "Pakistan's inheritance laws follow Islamic principles for Muslims.",
  "The Guardians and Wards Act governs custody and guardianship matters.",
  "Pakistan's rent laws provide protection to tenants against arbitrary eviction.",
  "The Urban Rent Restriction Ordinance varies by province in Pakistan.",
  "Pakistan's construction laws include building codes and safety regulations.",
  "The Pakistan Engineering Council regulates construction standards.",
  "Pakistan's environmental impact assessments are required for major projects.",
  "The Pakistan Environmental Protection Agency enforces environmental laws.",
  "Pakistan's water rights are governed by both federal and provincial laws.",
  "The Indus Water Treaty 1960 governs water sharing with India.",
  "Pakistan's energy laws regulate power generation and distribution.",
  "The National Electric Power Regulatory Authority (NEPRA) Act 1997 regulates electricity.",
  "Pakistan's oil and gas laws are governed by the Oil and Gas Regulatory Authority Ordinance 2002.",
]

